(function(){
'use strict';let passed=0;const checks=[];
function test(name,fn){fn();passed++;checks.push(name);}
function assert(v,message='Assertion échouée'){if(!v)throw Error(message);}
function equal(a,b){assert(a===b,JSON.stringify(a)+' !== '+JSON.stringify(b));}
const {Session,locations,digits,guessDigits,destination}=Preparation;
test('200 numéros uniques, parité, 34 travées de trois places par côté',()=>{const bins=locations();equal(bins.length,200);equal(new Set(bins.map(b=>b.number)).size,200);equal(bins[0].number,'1');equal(bins[199].number,'200');bins.forEach(b=>{equal(b.side,b.id%2?'left':'right');assert(b.slot>=0&&b.slot<3);assert(b.bay>=0&&b.bay<34);assert(/^\d{2}$/.test(b.code));assert(+b.code!==b.id);});equal(34*2*3-200,4);});
test('Voisins distincts, y compris entre travées, 100 parties',()=>{for(let i=0;i<100;i++){const bins=locations();for(let j=2;j<200;j++)assert(bins[j].code!==bins[j-2].code);}});
test('RNG constant ne bloque pas le tirage',()=>{const bins=locations(()=>0);for(let j=2;j<200;j++)assert(bins[j].code!==bins[j-2].code);});
test('10 à 50 BINs aléatoires mais croissants, puis nouveau couloir',()=>{const s=new Session();s.start();assert(s.aislePickLimit>=10&&s.aislePickLimit<=50);assert(s.aisleBinOrder.every((id,index,list)=>index===0||id>list[index-1]));const first=s.bin.id;s.next();assert(s.bin.id>first);s.aisleBinOrder=[6,50];s.aislePickLimit=2;s.picksInAisle=1;s.next();equal(s.bin.number,'50');const next=s.next();assert(s.bin.id>=1&&s.bin.id<=200);equal(next.newAisle,true);equal(next.aisle,2);assert(next.aislePickLimit>=10&&next.aislePickLimit<=50);});
test('Détrompeurs français : chiffres, accents, tirets, préfixes et nombres complets',()=>{equal(digits('deux, cinq'),'25');equal(digits('2 5'),'25');equal(digits('de 9'),'29');equal(digits('catin'),'41');equal(digits('catherine'),'41');equal(digits('Kit Kat'),'44');equal(digits('kiss cat'),'44');equal(digits('kisscat'),'44');equal(guessDigits('katine','41'),'41');equal(guessDigits('bonjour','41'),null);equal(digits('saint oui'),'58');equal(digits('cette neuve'),'79');equal(digits('zéro, neuf'),'09');equal(digits('25'),'25');equal(digits('six un'),'61');equal(digits('soixante et un'),'61');equal(digits('soixante-et-un'),'61');equal(digits('sept un'),'71');equal(digits('soixante et onze'),'71');equal(digits('soixante-douze'),'72');equal(digits('soixante-dix-neuf'),'79');equal(digits('quatre-vingt-deux'),'82');equal(digits('quatre-vingt-dix'),'90');equal(digits('quatre-vingt-dix-neuf'),'99');equal(digits('vingt-cinq'),'25');equal(digits('numéro détrompeur vingt-trois'),'23');equal(digits('code soixante-dix-huit'),'78');equal(digits('détrompeur vingt-trois alpha'),null);});
test('Destination exacte, quantité un obligatoire',()=>{equal(destination('Un Delta.'),3);equal(destination('1 delta'),3);equal(destination('Delta'),-1);equal(destination('deux Delta'),-1);equal(destination('Un Delta ou Alpha'),-1);});
test('Boucle directe : réponse vocale erronée sans pénalité, annonce et clic roll',()=>{const s=new Session();s.start(true);equal(s.bin.number,'150');equal(s.bin.code,'25');equal(s.deposit(3).ignored,true);equal(s.hear('quatre-vingt-deux').event,'retry');equal(s.errors,0);equal(s.phase,'code');equal(s.hear('numéro détrompeur vingt-cinq').say,'Un Delta');equal(s.phase,'roll');equal(s.deposit(3).event,'complete');equal(s.score,1);equal(s.deposit(3).ignored,true);s.next();equal(s.phase,'code');assert(!s.codeOK);equal(s.score,1);});
test('Alternatives : le code exact du BIN est accepté, les autres demandent une répétition',()=>{const s=new Session();s.start(true);equal(s.hear(['vingt-cinq','vingt-six']).say,'Un Delta');const ambiguous=new Session();ambiguous.start(true);equal(ambiguous.hear(['vingt-quatre','vingt-six']).event,'retry');equal(ambiguous.phase,'code');equal(ambiguous.errors,0);});
test('Erreurs ne valident rien : mauvais roll',()=>{const s=new Session();s.start(true);s.hear('25');s.deposit(0);equal(s.phase,'roll');equal(s.score,0);s.deposit(3);equal(s.score,1);});
test('Pause bloque voix et dépôt',()=>{const s=new Session();s.start(true);s.paused=true;assert(s.hear('deux cinq').ignored);s.paused=false;s.hear('deux cinq');s.paused=true;assert(s.deposit(3).ignored);equal(s.score,0);});
test('Codes stables entre commandes, renouvelés entre parties',()=>{let n=0;const s=new Session(()=>((n++%97)/97));s.start();const old=s.bins.map(b=>b.code).join();s.next();equal(s.bins.map(b=>b.code).join(),old);s.start();assert(s.bins.map(b=>b.code).join()!==old);});
test('Mode test respecte aussi tous les voisins',()=>{for(let i=0;i<100;i++){const s=new Session();s.start(true);for(let j=2;j<200;j++)assert(s.bins[j].code!==s.bins[j-2].code);}});
globalThis.TEST_REPORT={passed,checks};
})();
